### ISSUE TITLE
NGLP Request - Janeway API documentation

### ISSUE THREAD

**Issue by Pcolar** [NGLPteam/Requests#1]
Mauro & Martin: Could you provide a link to the Janeway API documentation for @zdavis at CIC?

**Comment by ajrbyers** [comment]
Currently there is a lack of docs for the API. An example of it can be found here:

https://www.openlibhums.org/api/

**Comment by zdavis** [comment]
Thanks, Andy. That's super helpful.

**Comment by Pcolar** [comment]
Thanks Andy!
